name: Validate Component Data

on:
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to the main branch
  push:
    branches:
      - main

jobs:
  validate-components:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install jsonschema

    - name: Run validation script
      run: python scripts/validate_components.py
